const mcqData = {
    "HTML": [
        { q: "What does HTML stand for?", options: ["Home Tool Markup Language", "Hyperlinks and Text Markup Language", "Hyper Text Markup Language", "Hyper Text Multiple Language"], a: 2 },
        { q: "Choose the correct HTML element for the largest heading:", options: ["<h1>", "<h6>", "<heading>", "<head>"], a: 0 },
        { q: "What is the correct HTML element for inserting a line break?", options: ["<lb>", "<break>", "<br>", "<newline>"], a: 2 },
        { q: "What is the correct HTML for adding a background color?", options: ["<body bg=\"yellow\">", "<background>yellow</background>", "<body style=\"background-color:yellow;\">", "<body color=\"yellow\">"], a: 2 },
        { q: "Choose the correct HTML element to define important text:", options: ["<b>", "<strong>", "<important>", "<i>"], a: 1 },
        { q: "Choose the correct HTML element to define emphasized text:", options: ["<italic>", "<i>", "<em>", "<strong>"], a: 2 },
        { q: "What is the correct HTML for creating a hyperlink?", options: ["<a href=\"http://www.w3schools.com\">W3Schools</a>", "<a url=\"http://www.w3schools.com\">W3Schools.com</a>", "<a>http://www.w3schools.com</a>", "<a name=\"http://www.w3schools.com\">W3Schools.com</a>"], a: 0 },
        { q: "Which character is used to indicate an end tag?", options: ["^", "/", "*", "<"], a: 1 },
        { q: "How can you open a link in a new tab/browser window?", options: ["<a href=\"url\" target=\"_blank\">", "<a href=\"url\" new>", "<a href=\"url\" target=\"new\">", "<a href=\"url\" window=\"new\">"], a: 0 },
        { q: "Which of these elements are all <table> elements?", options: ["<table><head><tfoot>", "<table><tr><td>", "<thead><body><tr>", "<table><tr><tt>"], a: 1 },
        { q: "Inline elements are normally displayed without starting a new line.", options: ["True", "False"], a: 0 },
        { q: "How can you make a numbered list?", options: ["<ul>", "<dl>", "<ol>", "<list>"], a: 2 },
        { q: "How can you make a bulleted list?", options: ["<list>", "<ol>", "<ul>", "<dl>"], a: 2 },
        { q: "What is the correct HTML for making a checkbox?", options: ["<checkbox>", "<input type=\"check\">", "<check>", "<input type=\"checkbox\">"], a: 3 },
        { q: "What is the correct HTML for making a text input field?", options: ["<textinput type=\"text\">", "<input type=\"text\">", "<input type=\"textfield\">", "<textfield>"], a: 1 },
        { q: "What is the correct HTML for making a drop-down list?", options: ["<list>", "<input type=\"dropdown\">", "<select>", "<input type=\"list\">"], a: 2 },
        { q: "What is the correct HTML for making a text area?", options: ["<textarea>", "<input type=\"textarea\">", "<input type=\"textbox\">", "<text>"], a: 0 },
        { q: "What is the correct HTML for inserting an image?", options: ["<img href=\"image.gif\" alt=\"MyImage\">", "<img alt=\"MyImage\">image.gif</img>", "<image src=\"image.gif\" alt=\"MyImage\">", "<img src=\"image.gif\" alt=\"MyImage\">"], a: 3 },
        { q: "Which HTML attribute specifies an alternate text for an image, if the image cannot be displayed?", options: ["title", "src", "alt", "longdesc"], a: 2 },
        { q: "Which doctype is correct for HTML5?", options: ["<!DOCTYPE html>", "<!DOCTYPE HTML5>", "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 5.0//EN\">", "<!DOCTYPE>"], a: 0 }
    ],
    "CSS": [
        { q: "What does CSS stand for?", options: ["Computer Style Sheets", "Creative Style Sheets", "Colorful Style Sheets", "Cascading Style Sheets"], a: 3 },
        { q: "What is the correct HTML for referring to an external style sheet?", options: ["<style src=\"mystyle.css\">", "<stylesheet>mystyle.css</stylesheet>", "<link rel=\"stylesheet\" type=\"text/css\" href=\"mystyle.css\">", "<link src=\"mystyle.css\">"], a: 2 },
        { q: "Where in an HTML document is the correct place to refer to an external style sheet?", options: ["In the <body> section", "At the end of the document", "In the <head> section", "Before the <html> tag"], a: 2 },
        { q: "Which HTML tag is used to define an internal style sheet?", options: ["<css>", "<script>", "<style>", "<link>"], a: 2 },
        { q: "Which HTML attribute is used to define inline styles?", options: ["class", "style", "font", "styles"], a: 1 },
        { q: "Which is the correct CSS syntax?", options: ["body:color=black;", "{body:color=black;}", "body {color: black;}", "{body;color:black;}"], a: 2 },
        { q: "How do you insert a comment in a CSS file?", options: ["// this is a comment //", "/* this is a comment */", "' this is a comment", "// this is a comment"], a: 1 },
        { q: "Which property is used to change the background color?", options: ["color", "bgcolor", "background-color", "bg-color"], a: 2 },
        { q: "How do you add a background color for all <h1> elements?", options: ["all.h1 {background-color:#FFFFFF;}", "h1.all {background-color:#FFFFFF;}", "h1 {background-color:#FFFFFF;}", "h1:all {background-color:#FFFFFF;}"], a: 2 },
        { q: "Which CSS property is used to change the text color of an element?", options: ["color", "text-color", "fgcolor", "font-color"], a: 0 },
        { q: "Which CSS property controls the text size?", options: ["text-size", "font-style", "text-style", "font-size"], a: 3 },
        { q: "What is the correct CSS syntax for making all the <p> elements bold?", options: ["p {text-size:bold;}", "p {font-weight:bold;}", "<p style=\"text-size:bold;\">", "<p style=\"font-size:bold;\">"], a: 1 },
        { q: "How do you display hyperlinks without an underline?", options: ["a {text-decoration:none;}", "a {decoration:no-underline;}", "a {text-decoration:no-underline;}", "a {underline:none;}"], a: 0 },
        { q: "How do you make each word in a text start with a capital letter?", options: ["text-transform:capitalize", "transform:capitalize", "text-style:capitalize", "You can't do that with CSS"], a: 0 },
        { q: "Which property is used to change the font of an element?", options: ["font-family", "font-weight", "font-style", "font-variant"], a: 0 },
        { q: "How do you make the text bold?", options: ["font:bold;", "style:bold;", "font-weight:bold;", "text-weight:bold;"], a: 2 },
        { q: "How do you select an element with id 'demo'?", options: ["demo", "#demo", ".demo", "*demo"], a: 1 },
        { q: "How do you select elements with class name 'test'?", options: ["test", "#test", ".test", "*test"], a: 2 },
        { q: "How do you select all p elements inside a div element?", options: ["div + p", "div.p", "div p", "div > p"], a: 2 },
        { q: "What is the default value of the position property?", options: ["relative", "fixed", "absolute", "static"], a: 3 }
    ],
    "JavaScript": [
        { q: "Inside which HTML element do we put the JavaScript?", options: ["<js>", "<scripting>", "<script>", "<javascript>"], a: 2 },
        { q: "What is the correct syntax for referring to an external script called 'xxx.js'?", options: ["<script name=\"xxx.js\">", "<script href=\"xxx.js\">", "<script src=\"xxx.js\">", "<script file=\"xxx.js\">"], a: 2 },
        { q: "The external JavaScript file must contain the <script> tag.", options: ["True", "False"], a: 1 },
        { q: "How do you write 'Hello World' in an alert box?", options: ["alertBox(\"Hello World\");", "msg(\"Hello World\");", "alert(\"Hello World\");", "msgBox(\"Hello World\");"], a: 2 },
        { q: "How do you create a function in JavaScript?", options: ["function myFunction()", "function:myFunction()", "function = myFunction()", "create myFunction()"], a: 0 },
        { q: "How do you call a function named 'myFunction'?", options: ["call function myFunction()", "myFunction()", "call myFunction()", "execute myFunction()"], a: 1 },
        { q: "How to write an IF statement in JavaScript?", options: ["if i = 5 then", "if i = 5", "if (i == 5)", "if i == 5 then"], a: 2 },
        { q: "How to write an IF statement for executing some code if 'i' is NOT equal to 5?", options: ["if (i != 5)", "if (i <> 5)", "if i <> 5", "if i =! 5 then"], a: 0 },
        { q: "How does a WHILE loop start?", options: ["while (i <= 10)", "while (i <= 10; i++)", "while i = 1 to 10", "until i == 10"], a: 0 },
        { q: "How does a FOR loop start?", options: ["for (i <= 5; i++)", "for (i = 0; i <= 5)", "for (i = 0; i <= 5; i++)", "for i = 1 to 5"], a: 2 },
        { q: "How can you add a comment in a JavaScript?", options: ["<!--This is a comment-->", "'This is a comment", "//This is a comment", "*This is a comment"], a: 2 },
        { q: "How to insert a comment that has more than one line?", options: ["/*This comment has more than one line*/", "<!--This comment has more than one line-->", "//This comment has more than one line//", "*/This comment has more than one line/*"], a: 0 },
        { q: "What is the correct way to write a JavaScript array?", options: ["var colors = \"red\", \"green\", \"blue\"", "var colors = 1 = (\"red\"), 2 = (\"green\"), 3 = (\"blue\")", "var colors = (1:\"red\", 2:\"green\", 3:\"blue\")", "var colors = [\"red\", \"green\", \"blue\"]"], a: 3 },
        { q: "How do you round the number 7.25, to the nearest integer?", options: ["Math.rnd(7.25)", "round(7.25)", "Math.round(7.25)", "rnd(7.25)"], a: 2 },
        { q: "How do you find the number with the highest value of x and y?", options: ["Math.ceil(x, y)", "Math.max(x, y)", "top(x, y)", "ceil(x, y)"], a: 1 },
        { q: "What is the correct JavaScript syntax for opening a new window called 'w2' ?", options: ["w2 = window.open(\"http://www.w3schools.com\");", "w2 = window.new(\"http://www.w3schools.com\");", "w2 = new window(\"http://www.w3schools.com\");", "w2 = open(\"http://www.w3schools.com\");"], a: 0 },
        { q: "JavaScript is the same as Java.", options: ["True", "False"], a: 1 },
        { q: "How can you detect the client's browser name?", options: ["client.navName", "navigator.appName", "browser.name", "window.browser"], a: 1 },
        { q: "Which event occurs when the user clicks on an HTML element?", options: ["onchange", "onmouseover", "onmouseclick", "onclick"], a: 3 },
        { q: "How do you declare a JavaScript variable?", options: ["v carName;", "variable carName;", "let carName;", "def carName;"], a: 2 }
    ],
    "DBMS": [
        { q: "What does DBMS stand for?", options: ["Database Management System", "Database Manipulation System", "Data Block Management System", "Digital Base Management System"], a: 0 },
        { q: "Which of the following is NOT an ACID property in DBMS?", options: ["Atomicity", "Consistency", "Isolation", "Availability"], a: 3 },
        { q: "What is the primary purpose of a primary key in a table?", options: ["To allow duplicate values", "To uniquely identify each record in a table", "To link two tables together", "To encrypt the table data"], a: 1 },
        { q: "Which SQL command is used to retrieve data from a database?", options: ["GET", "SELECT", "EXTRACT", "FETCH"], a: 1 },
        { q: "Which SQL JOIN returns all records from the left table and matched records from the right table?", options: ["INNER JOIN", "RIGHT JOIN", "FULL JOIN", "LEFT JOIN"], a: 3 },
        { q: "What is the default port for MySQL database?", options: ["1521", "3306", "5432", "27017"], a: 1 },
        { q: "Which SQL clause is used to filter records based on a specified condition?", options: ["GROUP BY", "ORDER BY", "WHERE", "HAVING"], a: 2 },
        { q: "What type of database is MongoDB?", options: ["Relational Database", "Key-Value store", "Document-oriented NoSQL Database", "Graph Database"], a: 2 },
        { q: "What does SQL stand for?", options: ["Structured Query Language", "Sequential Query Language", "Standard Query Language", "Simple Query Language"], a: 0 },
        { q: "What is data normalization used for in relational databases?", options: ["To increase data redundancy", "To reduce data redundancy and improve data integrity", "To encrypt sensitive data", "To speed up data insertion speeds"], a: 1 },
        { q: "Which normal form requires removing partial dependencies?", options: ["1NF", "2NF", "3NF", "BCNF"], a: 1 },
        { q: "Which command is used to completely remove a table and its data from a database?", options: ["DELETE TABLE", "DROP TABLE", "REMOVE TABLE", "TRUNCATE TABLE"], a: 1 },
        { q: "What is a foreign key?", options: ["A key defined in another database", "A key that uniquely identifies a row in its own table", "A key in one table that links to the primary key of another table", "A temporary key for backup purposes"], a: 2 },
        { q: "What is the purpose of a database Index?", options: ["To encrypt data", "To back up database tables", "To speed up data retrieval operations", "To compress database size"], a: 2 },
        { q: "What does the 'A' in ACID properties stand for?", options: ["Authorization", "Atomicity", "Availability", "Association"], a: 1 },
        { q: "Which statement is used to undo a transaction that has not yet been saved to the database?", options: ["COMMIT", "UNDO", "ROLLBACK", "REVOKE"], a: 2 },
        { q: "Which constraint ensures that all values in a column are unique?", options: ["PRIMARY KEY", "UNIQUE", "NOT NULL", "CHECK"], a: 1 },
        { q: "In NoSQL, what is denormalization primarily used for?", options: ["To save storage space", "To optimize read performance by combining data", "To enforce strict ACID properties", "To structure data into traditional tables"], a: 1 },
        { q: "Which of the following is a key-value store NoSQL database?", options: ["MongoDB", "PostgreSQL", "Redis", "Cassandra"], a: 2 },
        { q: "Which SQL function is used to count the number of rows in a query?", options: ["COUNT()", "SUM()", "TOTAL()", "ROWS()"], a: 0 }
    ]
};
